seed.js

Per discussion yesterday.
I thought about the difference between using `try-catch` inside the `async` function vs. using a final `.catch` on the promise that `seed` returns, and erred on the latter because it feels slightly more important to demonstrate that async functions always return promises. But I could be convinced otherwise.

add a seed file that does some async await explaining

---

package.json
script/deploy

I have observed students running into broken deploys and ending up in confusing interim states when they run `npm run deploy`. They are unexpectedly in a `deploy` branch.
Thoughts?

delete the deploy branch even when deploy fails

---

client/mock-axios.js
client/store/user.spec.js

I've had a couple students run into an issue when they attempt to create more tests around their store.
The `axios-mock-adapter` library is very confusing if you create two `MockAdapter`s wrapping the same axios adapter.
```js
import axios from 'axios'
import MockAdapter from 'axios-mock-adapter'
const mock1 = new MockAdapter(axios)
const mock2 = new MockAdapter(axios)
mock1.onGet('/path').reply(200, { some: 'data' })
axios.get('/path') // This will NOT match the `onGet('path')` specified above.
```
In practice `mock1` and `mock2` would be created in separate test files.
This happens because `axios-mock-adapter` overwrites a property on the `axios` instance passed into it: https://github.com/ctimmerm/axios-mock-adapter/blob/master/src/index.js#L39

move axios mocking to its own file

---

server/index.js

Students get horribly confused by this all the time. They aren't building a bundle, but instead of a 404, the server sends the index.html page. The browser tries to parse it as a script and logs "unexpected token <".
This PR adds a handler which sends 404s for any paths ending in a file extension. So if they request bundle.js and there is no bundle… 404. It still allows for the home page to be sent for any other path, e.g. `/about`.

fix(server): 404 for missing files

---

server/auth/google.js

In fixing conflicts to merge in the linter PR, one pair of parens was lost, resulting in an arrow-with-ambiguous-condition warning. This fixes that.

fix(linter): restore missing expression parens

---

client/store/user.js

---
If an auth error occurs, the user is signed out. If an error occurs *after* auth, it is caught and logged.

fix(redux/user): stop unrelated errors from logging out user during auth

---

package.json
server/db/db.js

This removes the hardcoded database url for testing and sets the default database name to be the package name (with '-test' at the end if the node env is testing).
Closes #34

fix(db): set database name to package name

---

package.json

---
Closes #69.
There were two options: whitelist (only watch `server`) or blacklist (ignore `public`, ignore `client`). The former would make more sense but if in the future we move the `db` out of `server` then I can foresee a nasty bug where people fail to realize that the Sequelize models changing doesn't cause a restart. The blacklist style is a little leaky, e.g. there could be false positives (editing the deploy script?), but that's better than failing to restart when necessary IMHO.

fix(nodemon): ignore client folder

---

server/db/models/user.js

---
Based on [this technique](https://github.com/sequelize/sequelize/issues/2132#issuecomment-341292873), hides the password and salt when serializing to JSON. Less brutal and bug-prone than overriding `toJSON`, too.
Closes #36.

feat(user): hide password and salt from client

---

.babelrc
package-lock.json
package.json
webpack.config.js

* Closes #76, closes #74.
* Fresher version of #20, but without actually converting any functions to `async`.
* Removed livereload plugin. Maybe later we can do better via #78.

feat(build): webpack 4, babel polyfill for async

---

.travis.yml
README.md

Enables automatic deployment from `master` after Travis tests pass, without having to move build dependencies from dev deps to normal deps. Although IMHO if you don't commit build artifacts (which we do not), then build deps _are_ production deps, but whatever – this PR makes the issue moot as it works anyway.

travis: set up for deployment

---

.babelrc

Please add a description of this Pull Request's motivation, scope, outstanding issues or potential alternatives, reasoning behind the current solution, and any other relevant information for posterity.
---
*Your PR Notes Here*
Since the past few days, I have been getting this error message 
```The new decorators proposal is not supported yet. You must pass the `"decoratorsLegacy": true` option to @babel/preset-stage-2```
After more research, it was determined that we have to add `"decoratorsLegacy": true` to `preset-stage-2` in the `.babelrc` file. 
You can find more info here: https://github.com/babel/babel/issues/7786

babel-preset-stage-2 fix

---

package.json

When the file path arguments to mocha are not wrapped in strings, the operating system expats them into file matches.
If we wrap the arguments in `'` quotes, they are passed into mocha and mocha uses a file glob module.
This way we need fewer matches to hit all the test files.

update mocha runner to use globs at node level

---

webpack.config.js

Please add a description of this Pull Request's motivation, scope, outstanding issues or potential alternatives, reasoning behind the current solution, and any other relevant information for posterity.
---
*Your PR Notes Here*
added `resolve` configuration in `webpack.config.js` to allow the importing of jsx files without putting .jsx at the end of the file name.

added support for importing jsx files without specifying a file type

---

client/store/user.js

Follows good practice by using `console.error` instead of `console.log` for error messages.

feat(error-handling): use console.error

---

README.md

Brings back the `--org` flag in the deployment instructions (accidentally steamrolled in a previous PR).
I went over the other changes with a fine-toothed comb and saw no other accidental deletions.

docs(readme): restore missing flag

---

package.json
script/encrypt-heroku-auth-token

Added a script to encrypt the Heroku auth token with bash tools, avoiding the need to install the Travis CLI tools. This script requires:
* `awk`
* `base64`
* `curl`
* `git`
* The Heroku CLI tools
* `node`
* `openssl`
* `sed`

feat(deployment): encrypt heroku auth token in bash

---

package.json

It appears that you need to specify the environment variable for the `&`ed child process as well.
Students were getting `pocess.env.NODE_ENV === undefined`.

set ENV vars on server process when running npm run start-dev

---

server/db/models/user.js

This ensures that any users created in bulk have their passwords automatically salted and hashed before they're saved to the database. It might not ever be necessary in a production environment, but can make seeding users easier.

fix(models): salt and hash passwords for bulk-created users

---

.travis.yml

Closes #162
The [default Node build script on Travis](https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#default-build-script) is to just run `npm test`. This PR augments the script to also build the bundle. A failing build (e.g. due to syntax errors or broken module paths) will thus fail Travis, making it harder for people to merge broken bundles (assuming their master branch is protected).

feat(travis): run build as part of testing

---

CHANGELOG.md
package-lock.json
package.json

* Updated Sequelize to its latest version which was released about 15 hours ago to fix a security vulnerability
Keeping the packages updated 
---

Updated sequelize to 5.3.1

---

server/index.js

Sequelize v5 no longer supports the `Model.findById` method: it's been replaced by `findByPk`. We were still using `findById` in the `deserializeUser` function, which threw an error when a user signed in.

replaces deprecated findById with findByPk

---

client/history.js

Uses named exports from history to remove deprecation warnings
closes #173

fixes history deprecation warning

---

server/db/db.js

Due to a recent update on Heroku SSL is needed for postgres connections. This PR adds the necessary options in our Sequelize connection instance so that deployment works.

adds ssl config
