FullstackAcademy/boilermaker

README.md, client/components/Main.js, package.json
Reverts FullstackAcademy/boilermaker#1
=> Revert "Production build"

package.json, server/index.js, yarn.lock
=> add compression middleware

package.json, script/seed.js
=> add seed to script directory

package.json, server/auth/google.js
=> fix(testing): init secrets, skip missing OAuth so tests work

client/store/index.js, package.json, yarn.lock
Connects redux devtools. Super useful for pedagogy, debugging, etc.
=> feat(devtools): redux devtools

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Improves disciplined collaboration by automatically reminding students of requirements when making PRs or issues.
=> GitHub Templates

client/routes.js, package.json
Please add a description of this Pull Request's motivation, scope, outstanding issues or potential alternatives, reasoning behind the current solution, and any other relevant information for posterity.
---
I tested the code (ran the tests and made sure it runs in the browser). I also updated the package.json
=> Update to only user RR4

server/auth/index.js
Whoops - forgot to destroy the entire session on logout, not just req.user.
=> destroy session properly on logout

README.md
Updates readme to reflect change in db naming behavior.
=> fix(readme): change to reflect new db naming behavior

.travis.yml, README.md
travis: skip cleanup
fix(travis): hyphenated db name
fix(travis): actually allow hyphen
feat(travis): rearrange, include latent build
---
Enables easy continuous testing with Travis-CI. Actually-factually tried it out and got it working. Note, this is just the testing phase; deployment is still inactive.
=> travis: add .travis.yml

README.md
=> docs(README): add --org flag to travis encrypt

server/auth/index.js
=> feat(login): restrict details on failed login

server/auth/google.js
Closes #99.
**Not yet tested.** Please confirm by running with an actual OAuth login before merging.
=> refactor(auth/google): use `findOrCreate`

.travis.yml
=> feat(travis): remove outdated npm upgrade

package-lock.json, package.json, server/db/db.js, server/index.js
This PR:
- addresses known vulnerabilities as reported by GitHub / npm.
- fixes resource deallocation bugs, allowing Mocha to exit properly
- closes the database after tests run
- closes the session store after tests run
=> fix(versions, mocha): remove vulnerabilities and deallocate resources

package.json, server/index.js
=> feat(server): switch to built-in body parser

server/auth/index.js
=> fix(login): restore missing error handling

package.json
=> feat(prettier): make prettier opt-out

webpack.config.js
Don't watch node_modules for changes.
=> don't watch node_modules

package-lock.json, package.json
Just updates mocha. Tests still seem to run fine. Since it's a minor version change, it shouldn't break anything (praying to the gods of semver).
closes #180
=> just updates mocha

package-lock.json, package.json
=> chore: upgraded axios to 0.19

.travis.yml, package.json
Checking if the travis node version is causing build issues.
=> Pin node version to 12 on travis

.travis.yml, package-lock.json, package.json
Updates version of pg to be compatible with Node 14
=> updates version of pg
